apiVersion: v1
kind: Secret
metadata:
  name: db-connection-secret
type: Opaque
data:
  connection-string: U2VydmVyPXRjcDpldGlja2V0ZGJzZXJ2ZXIuZGF0YWJhc2Uud2luZG93cy5uZXQsMTQzMztJbml0aWFsIENhdGFsb2c9ZXRpY2tldC1kYjtQZXJzaXN0IFNlY3VyaXR5IEluZm89RmFsc2U7VXNlciBJRD1tYWhtb3VkO1Bhc3N3b3JkPXM3VmlfV1AwNHdEZTtNdWx0aXBsZUFjdGl2ZVJlc3VsdFNldHM9RmFsc2U7RW5jcnlwdD1UcnVlO1RydXN0U2VydmVyQ2VydGlmaWNhdGU9RmFsc2U7Q29ubmVjdGlvbiBUaW1lb3V0PTMwOw==
# Server=tcp:eticketdbserver.database.windows.net,1433;Initial Catalog=eticket-db;Persist Security Info=False;User ID=mahmoud;Password={your_password};MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;